name: Test Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deployment:
    name: Deploy Frontend on Remote Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.0.0' # Use the appropriate Node.js version for your project

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Install private SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add server's public SSH key to known hosts
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

      - name: Deploy frontend
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}
        run: |
          rsync -avz --delete ./build/ $SSH_USER@$SSH_HOST:$DEPLOY_DIR

      - name: Cleanup
        run: rm -rf ~/.ssh
